### ISSUE TITLE
"hcitool scan" does not return any results

### ISSUE THREAD

**Issue by floion** [balena-os/balena-edison#128]
Lastly observed on 2.13.6+rev1 but present on earlier releases also 

Running "hcitool scan" the prompt never returns.

Also, dmesg shows the following:

> [   18.645179] Bluetooth: hci0: last event is not cmd complete (0x0f)
[   28.904285] Bluetooth: hci0: Frame reassembly failed (-84)
[   28.909911] Bluetooth: hci0: Frame reassembly failed (-84)

**Comment by horia-delicoti** [comment]
Attaching more logs that could help: [flowdock 2.29.0+rev1](https://www.flowdock.com/app/rulemotion/device-testing/threads/WmrsfLssuJx_cQd9hx7MAVrxLm2)

**Comment by acostach** [comment]
Looking into this we can see that bluetooth actually works, it's hcitool that's not supported for this device.

`root@13ac6d7:~# btmgmt find `
`Discovery started`
`hci0 type 7 discovering on`
`hci0 dev_found: 58:B1:0F:11:2C:49 type BR/EDR rssi -26 flags 0x0000 `
`name Galaxy A8 (2018)`
`hci0 type 7 discovering off`

Using bluetootcth and `dbus-monitor --system |grep blue &` we can inspect the dbus methods called and then test them as well: 
`export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket`
`dbus-send --system --type=method_call --print-reply --dest=org.bluez "/" org.freedesktop.DBus.ObjectManager.GetManagedObjects`
`dict entry(`
		` object path "/org/bluez/hci0/dev_58_B1_0F_11_2C_XX"`
...
`dict entry(`
 ` string "Address"`
 `variant     string "58:B1:0F:11:2C:XX"`
...
 `string "Name"`
  `variant    string "Galaxy A8 (2018)"`
...
or trigger scanning:
`dbus-send --system --type=method_call --print-reply --dest=org.bluez "/org/bluez/hci0" org.bluez.Adapter1.StartDiscovery`

The root cause for this is that support has been [dropped](https://www.spinics.net/lists/linux-bluetooth/msg70489.html) for tools like hcitool, hciconfig in favor of the bluez management interface. In support forums Intel also recommends using bluetoothctl on Edison as a response to this issue.

I have raised https://github.com/balena-io-playground/test-bluetooth/pull/2 to use bluetoothctl when testing Edison
